SmartcardException: store the PC/SC return code in hresult
Change the SmartcardException class to be able to store the PC/SC return
code in the hresult field.
This can be used to check for the PC/SC error causing the exception and
differentiate two exceptions of the same class.