PCSCExceptions: add support for BaseSCardException(hresult)
The normal syntax should be BaseSCardException(hresult=hresult) but I
hvae some old code that still uses BaseSCardException(hresult)

We now get:
smartcard.pcsc.PCSCExceptions.BaseSCardException: scard exception: RPC transport error. (0x80100013)
instead of:
smartcard.pcsc.PCSCExceptions.BaseSCardException: 2148532243