SCardStatus(): Fix a crash in case of PC/SC error
If SCardStatus() returns an error code then the readername parameter is
not set. So the memory contains random bytes returned by mem_Malloc().

This resulted in strange errors like:
SystemError: ../Objects/listobject.c:305: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./transmit_card_removed.py", line 72, in <module>
    hresult, reader, state, protocol, atr = SCardStatus(hcard)
  File "/usr/local/lib/python3.7/dist-packages/pyscard-1.9.9-py3.7-linux-x86_64.egg/smartcard/scard/scard.py", line 822, in SCardStatus
    return _scard.SCardStatus(hcard)
SystemError: <built-in function SCardStatus> returned a result with an error set

The code now initialize the reader name with a NUL terminated empty
string.