Python3: define basestring so it works on Python 3
Fixes error:
  File ".../pyscard/smartcard/Synchronization.py", line 32, in synchronize

    if isinstance(names, basestring):

NameError: name 'basestring' is not defined