Exceptions: remove extra ": " in the message
The text message for CardConnectionException(hresult=SCARD_E_NO_SERVICE)
is now:
smartcard.Exceptions.CardConnectionException: Service not available. (0x8010001D)
instead of:
smartcard.Exceptions.CardConnectionException: : Service not available. (0x8010001D)