AppVeyor: remove bdist_wininst as it fails on Python 3.10
%CMD_IN_ENV% python setup.py bdist_wininst
Using default MSVC build environment for 64 bit architecture
Executing: python setup.py bdist_wininst
C:\projects\pyscard-debug\setup.py:28: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import get_platform
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: invalid command 'bdist_wininst'
Command exited with code 1