Add an explicit .close() method to CardConnection()
Thanks to Mike Kazantsev for the bug report
"PCSCCardConnection.__del__ method raises exceptions that cannot be easily handled in python code. #223"
Closes: https://github.com/LudovicRousseau/pyscard/issues/223

Describe the bug

PCSCCardConnection.__del__ method raises exceptions that cannot be
easily handled in python code.

To Reproduce

I have a code that does something along the lines of:

req = smartcard.CardRequest.CardRequest(...)
svc = req.waitforcard()
svc.connection.connect()
svc.connection.transmit(cmd)
svc.connection.disconnect()
sleep(...)
exit()

Sometimes this raises following exception:

Exception ignored in: <function PCSCCardConnection.__del__ at 0x7fad81c78fe0>
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 90, in __del__
    raise CardConnectionException(
smartcard.Exceptions.CardConnectionException: Failed to release context: Service not available.: Service not available. (0x8010001D)

As far as I can tell, it gets raised during python's internal garbage
collection, so cannot easily be handled by code, as GC is supposed to
not be directly controlled by python code (aside from some hacks in "gc"
module and ordering duarantees iirc).

Expected behavior

Context can be closed manually within the usual try: ... except: ...
statements, so that any exceptions raised when closing it can be handled
properly.

Additional context

Workaround can be using del svc or such statements, but there's no
guarantee it'd trigger GC, and pretty sure they won't call __del__
method within try-except context anyway, resulting in same uncatchable
exception, just at a different time.

Running SCardReleaseContext(svc.connection.component.hcontext) looks
like going too deep into internals, and hence a bad way to do it, and
does not solve the issue, as it guarantees that __del__ method will now
fail with "Invalid handle." error.
But it at least allows to get Service not available. error out of there
to handle.

I think simple fix might be to add some kind of svc.close() method
and/or python's context management (with ... as ...: ... statement) for
such objects, which will completely close everything that code creates,
with nothing implicit left to run later (except for maybe trivial object
cleanups with no side-effects).

Iirc I've looked into this wrt pyscard managing pcsc-lite connection
lifecycle, and bumped into same general issue, of it not being
explicitly controllable.  Which led me to conclude that pyscard module
can only be used within its own subprocess that gets killed after use,
otherwise there's no way to tell it to "close pcsc-lite connection to
allow pcsc-lite to auto-exit", and what looks to be implicit-only
context management here seem to also be a symptom of that.