PCSCCardConnection.disconnect: always reset .hcard value
We reset self.hcard to None in all cases, even in case of error. So that
the next time disconnect() is called we will not try, again, to
disconnect.

The problem was visible when using a smartcard.Session() and we
disconnect the reader before the end of the session. When the program
exists we had something like:

Exception ignored in: <function CardService.__del__ at 0x7f0e096b76d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyscard-2.0.3-py3.10-linux-x86_64.egg/smartcard/CardService.py", line 51, in __del__
  File "/usr/local/lib/python3.10/dist-packages/pyscard-2.0.3-py3.10-linux-x86_64.egg/smartcard/CardConnectionDecorator.py", line 62, in disconnect
  File "/usr/local/lib/python3.10/dist-packages/pyscard-2.0.3-py3.10-linux-x86_64.egg/smartcard/pcsc/PCSCCardConnection.py", line 201, in disconnect
smartcard.Exceptions.CardConnectionException: Failed to disconnect: Invalid value given.
Exception ignored in: <function PCSCCardConnection.__del__ at 0x7f0e096b57e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyscard-2.0.3-py3.10-linux-x86_64.egg/smartcard/pcsc/PCSCCardConnection.py", line 87, in __del__
  File "/usr/local/lib/python3.10/dist-packages/pyscard-2.0.3-py3.10-linux-x86_64.egg/smartcard/pcsc/PCSCCardConnection.py", line 201, in disconnect
smartcard.Exceptions.CardConnectionException: Failed to disconnect: Invalid value given.

The first disconnect() failed with SCARD_E_INVALID_VALUE (because the
reader has been removed). This exception was catched.
The 2 other disconnect() also failed with the same error but the
exceptions are not catched.

Thanks to Frank Morgner for the bug report
" Quitting Session causes "Exception ignored in" #131 "
https://github.com/LudovicRousseau/pyscard/issues/131