setup.py: fix for Python 2.6
With Python 2.6 on Mac OS X 10.11 I got an error:
$ ./setup.py install
running install
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 195, in <module>
    setup(**kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "./setup.py", line 103, in run
    if self._called_from_setup:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
    raise AttributeError, attr
AttributeError: _called_from_setup

Now _called_from_setup() is called only if it exists.